eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: User
          uri: http://localhost:9098
          predicates:
            - Path=/user/**
        - id: Order
          uri: http://localhost:9091
          predicates:
            - Path=/order/**
