eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9091
spring:
  application:
    name: Order
  datasource:
    url: jdbc:mysql://localhost:3306/dump
    username: root
    password: pass@word1
  cloud:
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

